#include "arduino_secrets.h"
/* 

  Sketch generated by the Arduino IoT Cloud Thing "Group10" 

  https://create.arduino.cc/cloud/things/39fd4e65-54f4-4b21-987c-901a2acf01dd  

  

  Arduino IoT Cloud Variables description 

  

  The following variables are automatically generated and updated when changes are made to the Thing 

  

  float temperature; 

  int soil_moisture; 


*/ 

  

#include "thingProperties.h" 

#include <Arduino_MKRIoTCarrier.h> 

  

MKRIoTCarrier carrier; 

  

// Soil moisture pin (as per reference sheet) 

int moistPin = A0; 

  

void setup() { 

  // Initialize serial and wait for port to open: 

  Serial.begin(9600); 

  delay(1500);  

  

  // Defined in thingProperties.h 

  initProperties(); 

  

  // Connect to Arduino IoT Cloud 

  ArduinoCloud.begin(ArduinoIoTPreferredConnection); 

  

  setDebugMessageLevel(2); 

  ArduinoCloud.printDebugInfo(); 

  

  // Initialize IoT Carrier 

  CARRIER_CASE = true; 

  carrier.begin(); 

  

  Serial.println("System initialized. Connecting to Cloud..."); 

  

  // Wait until connected 

  while (!ArduinoCloud.connected()) { 

    ArduinoCloud.update(); 

  

    carrier.display.fillScreen(ST77XX_BLACK); 

    carrier.display.setTextColor(ST77XX_WHITE); 

    carrier.display.setTextSize(2); 

    carrier.display.setCursor(20, 80); 

    carrier.display.println("Connecting..."); 

  

    delay(500); 

  } 

  

  Serial.println("Connected to Arduino IoT Cloud!"); 

} 

  

void loop() { 

  ArduinoCloud.update(); 

  

  // ── Read Temperature from IoT Carrier ── 

  temperature = carrier.Env.readTemperature(); 

  

  // ── Read Soil Moisture (analog sensor on A6) ── 

  int rawMoisture = analogRead(moistPin); 

  

  // Map to percentage (adjusted: wet → high %) 

  soil_moisture = map(rawMoisture, 1023, 0, 0, 100); 

  

  // Debug prints 

  Serial.print("Temperature (°C): "); 

  Serial.println(temperature); 

  

  Serial.print("Soil Moisture (%): "); 

  Serial.println(soil_moisture); 

  

  // Display on screen (optional but good for marks) 

  carrier.display.fillScreen(ST77XX_BLACK); 

  carrier.display.setTextColor(ST77XX_GREEN); 

  carrier.display.setTextSize(2); 

  

  carrier.display.setCursor(10, 50); 

  carrier.display.print("Temp: "); 

  carrier.display.print(temperature); 

  

  carrier.display.setCursor(10, 90); 

  carrier.display.print("Soil: "); 

  carrier.display.print(soil_moisture); 

  

  delay(5000);  // Matches your periodic update 

} 

  

/* 

  Since temperature is READ_ONLY, this function is called 

  whenever the value is changed from the Arduino Cloud Dashboard. 

*/ 

void onTemperatureChange() { 

  Serial.print("Temperature updated from Cloud: "); 

  Serial.println(temperature); 

} 

  

/* 

  Since soil_moisture is READ_ONLY, this function is called 

  whenever the value is changed from the Arduino Cloud Dashboard. 

*/ 

void onSoilMoistureChange() { 

  Serial.print("Soil Moisture updated from Cloud: "); 

  Serial.println(soil_moisture); 

} 